
name: CIワークフロー

on:
  push:
    branches:
      - main # mainブランチへのpushで実行
  pull_request:
    branches:
      - main # mainブランチへのプルリクエストで実行

jobs:
  build:
    runs-on: ubuntu-latest # Ubuntu環境で実行

    steps:
    # リポジトリのコードをチェックアウト
    - name: コードをチェックアウト
      uses: actions/checkout@v3

    # Node.jsをセットアップ（JavaScript/Node.js用プロジェクトの場合）
    - name: Node.jsをセットアップ
      uses: actions/setup-node@v3
      with:
        node-version: 18 # Node.jsのバージョンを指定

    # 依存パッケージのインストール
    - name: 依存関係をインストール
      run: npm install

    # テストの実行
    - name: テストを実行
      run: npm test

    # （オプション）コードのLintチェック
    - name: Lintチェック
      run: npm run lint
